language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
  - extra-android-support
# after_success:
#   - ".buildscript/deploy_snapshot.sh"
jdk:
  - oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
script: "./gradlew check"
before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
sudo: false
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
