name: Build/Test

on:
  # Trigger on every pull request
  pull_request:
  # This is reused in deploy_snapshot.yml
  workflow_call:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RxGroups
        uses: actions/checkout@v2
      - name: Build/Test RxGroups
        run: ./gradlew check