name: Deploy snapshot

on:
  # Trigger ONLY on push to master branch
  push:
    branches:
      - master
jobs:
  build-test:
    uses: airbnb/RxGroups/.github/workflows/build_test.yml@master
  deploy-snapshot:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RxGroups
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: liberica
          java-version: '8'
      - name: NDK workaround
        run: mkdir -p $ANDROID_HOME/ndk-bundle/toolchains/mips64el-linux-android/prebuilt/linux-x86_64
      - name: Create sytem gradle.properties
        env:
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
      - name: Deploy new snapshot of RxGroups
        shell: bash
        run: ./gradlew uploadArchives
