name: Deploy snapshot

on:
  # Trigger ONLY on push to master branch
  push:
    branches:
      - master
jobs:
  build-test:
    uses: airbnb/RxGroups/.github/workflows/build_test.yml@master
  deploy-snapshot:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout RxGroups
        uses: actions/checkout@v2
      - name: Deploy new snapshot of RxGroups
        shell: bash
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: ./gradlew uploadArchives
